### PR TITLE
blog post for numpy

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by jukent** [comment]
@kmpaul This blog post is a result from our conversation about making all of the announcement information public and findable. Do you think I should be explicit about the Zoom link -- or it being on the calendar is good enough?

@pilotchute Let me know if what is written here best reflects how you'd like to advertise the contents of the seminar.

**Comment by jukent** [comment]
I'll hold off on this until the Colab/notebook discussion is resolved.

**Comment by jukent** [comment]
@pilotchute Could you take a loot at this so that I can publish it and submit a link to itt to staff notes daily before the end of the day? 

I am out Monday and Tuesday so ideally I'd like to get the advertisements/announcements out before I am off for the weekend.

**Review by pilotchute — APPROVED** [review]
Looks good to me!

**Pull request merged**
