### PR TITLE
Xarray

### PR DESCRIPTION
**Pull request by jukent**
Xarray announcement

### CODE REVIEW

**Comment by jukent** [comment]
@mgrover1 Anderson is offline for the rest of the day, so I was hoping you would have time to read over this for typos so it can be published this afternoon. I'd really appreciate it :)

**Comment by mgrover1** [comment]
Looks fantastic! Just a few minor changes
* Change "Mountain" to "Mountain Standard Time"
* Can you add Anderson's github link ([Anderson Banihirwe](https://github.com/andersy005)
* Add a period after "this session will be led by..."
* Change MT to MST

**Review by mgrover1 — COMMENTED** [review]
Please see the comments I left in the thread - once that is good to go, looks great!!

**Comment by jukent** [comment]
> @jukent Looks fantastic! Just a few minor changes
> 
> * Change "Mountain" to "Mountain Standard Time"
> * Can you add Anderson's github link ([Anderson Banihirwe](https://github.com/andersy005))
> * Add a period after "this session will be led by..."
> * Change MT to MST

We're in daylight time right now btw.

**Comment by mgrover1** [comment]
> We're in daylight time right now btw.
Ope you right - sorry about that! Good catch...

**Pull request merged**
